gpt4_format_correctness:
  prompt_template: "gpt4_format_correctness/alpaca_eval.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4"
    max_tokens: 1024
    temperature: 0
  fn_completion_parser: "json_parser"
  key_in_completion: "format_correctness"
  batch_size: 1
