# alpaca eval is
alpaca_eval_gpt4_content_correctness:
  prompt_template: "alpaca_eval_gpt4_content_correctness/alpaca_eval.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4-1106-preview"
    max_tokens: 1024
    temperature: 0
    response_format:
      "type": "json_object"
  fn_completion_parser: "json_parser"
  key_in_completion: "content_correctness"
  batch_size: 1
