# alpaca eval is
alpaca_eval_gpt4:
  prompt_template: "alpaca_eval_gpt4_correctness/alpaca_eval.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4"
    max_tokens: 1024
    temperature: 0
  fn_completion_parser: "ranking_parser_two_outputs"
  batch_size: 1
